# 그룹연산

## groupby 메서드로 평균값 구하기

In [1]:
import pandas as pd 
df = pd.read_csv('data/gapminder.tsv', sep='\t')

In [2]:
#평균값 구하기 
#lifeExp(기대 수명)열의 연도별 평균값 
avg_life_exp_by_year = df.groupby('year').lifeExp.mean() 


## 분할-반영-결합 과정 살펴보기

In [3]:
#분할 
#groupby메서드에 열이름을 전달하면 분할 작업이 일어난다. 
years = df.year.unique() 


In [4]:
#연도별 데이터 추출하여 
y1952 = df.loc[df.year == 1952, :] 
print(y1952.head())

        country continent  year  lifeExp       pop    gdpPercap
0   Afghanistan      Asia  1952   28.801   8425333   779.445314
12      Albania    Europe  1952   55.230   1282697  1601.056136
24      Algeria    Africa  1952   43.077   9279525  2449.008185
36       Angola    Africa  1952   30.015   4232095  3520.610273
48    Argentina  Americas  1952   62.485  17876956  5911.315053


In [5]:
#lifeExp열의 평균을 구하는 작업이 반영이다....
y1952_mean = y1952.lifeExp.mean() 
print(y1952_mean)

49.05761971830987


In [6]:
#반영
y1957 = df.loc[df.year == 1957, :] 
y1957_mean = y1957.lifeExp.mean( )
print(y1957_mean)

y1962 = df.loc[df.year == 1962, :] 
y1962_mean = y1962.lifeExp.mean( )
print(y1962_mean)

y2007 = df.loc[df.year == 2007, :] 
y2007_mean = y2007.lifeExp.mean( )
print(y2007_mean)

51.50740112676054
53.60924901408449
67.00742253521126


In [7]:
#결합
df2 = pd.DataFrame({"year":[1952, 1957, 1962, 2007], 
                    "평균":[y1952_mean, y1957_mean,y1962_mean,y2007_mean]}) 
print(df2)

   year         평균
0  1952  49.057620
1  1957  51.507401
2  1962  53.609249
3  2007  67.007423


## 평균값을 구하는 사용자 함수와 groupby 메서드

In [59]:
df[df.year==1952]

country continent  year  lifeExp       pop    gdpPercap
0            Afghanistan      Asia  1952   28.801   8425333   779.445314
12               Albania    Europe  1952   55.230   1282697  1601.056136
24               Algeria    Africa  1952   43.077   9279525  2449.008185
36                Angola    Africa  1952   30.015   4232095  3520.610273
48             Argentina  Americas  1952   62.485  17876956  5911.315053
...                  ...       ...   ...      ...       ...          ...
1644             Vietnam      Asia  1952   40.412  26246839   605.066492
1656  West Bank and Gaza      Asia  1952   43.160   1030585  1515.592329
1668         Yemen, Rep.      Asia  1952   32.548   4963829   781.717576
1680              Zambia    Africa  1952   42.038   2672000  1147.388831
1692            Zimbabwe    Africa  1952   48.451   3080907   406.884115

[142 rows x 6 columns]

In [8]:
df[df.year==1952].sum()

country      AfghanistanAlbaniaAlgeriaAngolaArgentinaAustra...
continent    AsiaEuropeAfricaAfricaAmericasOceaniaEuropeAsi...
year                                                    277184
lifeExp                                                6966.18
pop                                                 2406957150
gdpPercap                                               528989
dtype: object

In [9]:
print(df.groupby("year").count(), end="누락값을 제외한 데이터 수 \n")
print(df.groupby("year").sum(), end="전체합\n")  
print(df.groupby("year").mean(), end="평균값\n") 
print(df.groupby("year").std(), end="표준편차\n") 
print(df.groupby("year").min(), end="최소값\n") 
print(df.groupby("year").max(), end="최대값 \n") 
print(df.groupby("year").var(), end="분산\n")  
print(df.groupby("year")["lifeExp","pop","gdpPercap"].quantile(q=0.25) , end="백분위수 25% \n")
print(df.groupby("year")["lifeExp","pop","gdpPercap"].quantile(q=0.5), end="백분위수 50% \n") 
print(df.groupby("year")["lifeExp","pop","gdpPercap"].quantile(q=0.75), end="백분위수 75% \n") 
print(df.groupby("year").size(), end="누락값을 포함한 데이터수  \n") 
print(df.groupby("year").first(), end="첫번째 행 반환\n")  
print(df.groupby("year").last(), end="마지막행 반환\n")  
print(df.groupby("year").nth(1), end="n번째 행 반환 \n")  

df.lifeExp.mean()

      country  continent  lifeExp  pop  gdpPercap
year                                             
1952      142        142      142  142        142
1957      142        142      142  142        142
1962      142        142      142  142        142
1967      142        142      142  142        142
1972      142        142      142  142        142
1977      142        142      142  142        142
1982      142        142      142  142        142
1987      142        142      142  142        142
1992      142        142      142  142        142
1997      142        142      142  142        142
2002      142        142      142  142        142
2007      142        142      142  142        142누락값을 제외한 데이터 수 
         lifeExp         pop     gdpPercap
year                                      
1952  6966.18200  2406957150  5.289892e+05
1957  7314.05096  2664404580  6.105160e+05
1962  7612.51336  2899782974  6.710654e+05
1967  7906.31712  3217478384  7.786787e+05
1972  8185.92888  357697715

<ipython-input-9-44a18056bc8e>:8: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  print(df.groupby("year")["lifeExp","pop","gdpPercap"].quantile(q=0.25) , end="백분위수 25% \n")
<ipython-input-9-44a18056bc8e>:9: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  print(df.groupby("year")["lifeExp","pop","gdpPercap"].quantile(q=0.5), end="백분위수 50% \n")
<ipython-input-9-44a18056bc8e>:10: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  print(df.groupby("year")["lifeExp","pop","gdpPercap"].quantile(q=0.75), end="백분위수 75% \n")


59.47443936619713

In [10]:
df.groupby("year").describe().head(n=3)

lifeExp                                                                   \
       count       mean        std     min      25%      50%       75%    max   
year                                                                            
1952   142.0  49.057620  12.225956  28.801  39.0590  45.1355  59.76500  72.67   
1957   142.0  51.507401  12.231286  30.332  41.2475  48.3605  63.03675  73.47   
1962   142.0  53.609249  12.097245  31.997  43.4685  50.8810  65.23450  73.68   

        pop                ...                           gdpPercap  \
      count          mean  ...          75%          max     count   
year                       ...                                       
1952  142.0  1.695040e+07  ...   9168197.75  556263527.0     142.0   
1957  142.0  1.876341e+07  ...   9817598.00  637408000.0     142.0   
1962  142.0  2.042101e+07  ...  10980084.50  665770000.0     142.0   

                                                                      \
             mean          std         min          25%          50%   
year                                                                   
1952  3725.276046  9321.064786  298.846212   864.752389  1968.528344   
1957  4299.408345  9869.662202  335.997115   930.540819  2173.220291   
1962  4725.812342  8667.362525  355.203227  1059.149171  2335.439533   

                                 
              75%           max  
year                             
1952  3913.492777  108382.35290  
1957  4876.356362  113523.13290  
1962  5709.381428   95458.11176  

[3 rows x 24 columns]

In [11]:
def my_mean(values):
    n = len(values)
    
    sum = 0 
    for value in values:
        sum += value
    
    return sum / n

In [12]:
#사용자함수와 groupby메서드 조합하려면 : agg메서드 
agg_my_mean = df.groupby('year').lifeExp.agg(my_mean) 
print(agg_my_mean)

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64


## 두 개의 인자값을 받아 처리하는 사용자 함수와 groupby 메서드

In [13]:
#연도별 평균수명에서 전체 평균수명을 뺀 값을 계산하기 위해 함수를 만들기 
def my_mean_diff(values, diff_value):
    n = len(values) 
    sum = 0 
    for value in values:
        sum += value 
    mean = sum / n 
    return mean - diff_value

In [14]:
#전체평균수명 
global_mean = df.lifeExp.mean() 
print(global_mean)

59.47443936619713


In [15]:
#연도별 평균수명에서 전체평균수명을 뺀 값 구하기  diff_value=global_mean 또는 global_mean
agg_mean_diff = df.groupby('year').lifeExp.agg(my_mean_diff, diff_value=global_mean) 
print(agg_mean_diff)

year
1952   -10.416820
1957    -7.967038
1962    -5.865190
1967    -3.796150
1972    -1.827053
1977     0.095718
1982     2.058758
1987     3.738173
1992     4.685899
1997     5.540237
2002     6.220483
2007     7.532983
Name: lifeExp, dtype: float64


## 집계 메서드를 리스트, 딕셔너리에 담아 전달

In [16]:
#년도별 lifeExp칼럼으로 그룹화
#....lifeExp열의 0이 아닌 값의 개수, 평균, 표준편차를 list에 담아 한번에 계산하여 출력
import numpy as np
gdf = df.groupby('year').lifeExp.agg([np.count_nonzero, np.mean, np.std]) 
gdf

count_nonzero       mean        std
year                                     
1952          142.0  49.057620  12.225956
1957          142.0  51.507401  12.231286
1962          142.0  53.609249  12.097245
1967          142.0  55.678290  11.718858
1972          142.0  57.647386  11.381953
1977          142.0  59.570157  11.227229
1982          142.0  61.533197  10.770618
1987          142.0  63.212613  10.556285
1992          142.0  64.160338  11.227380
1997          142.0  65.014676  11.559439
2002          142.0  65.694923  12.279823
2007          142.0  67.007423  12.073021

In [17]:
#연도별 그룹화....열이름과 집계메서드를 dictionary로 전달
gdf_dict = df.groupby('year').agg({'lifeExp': 'mean', 'pop': 'median', 'gdpPercap': 'median'}) 
gdf_dict

lifeExp         pop    gdpPercap
year                                    
1952  49.057620   3943953.0  1968.528344
1957  51.507401   4282942.0  2173.220291
1962  53.609249   4686039.5  2335.439533
1967  55.678290   5170175.5  2678.334741
1972  57.647386   5877996.5  3339.129407
1977  59.570157   6404036.5  3798.609244
1982  61.533197   7007320.0  4216.228428
1987  63.212613   7774861.5  4280.300366
1992  64.160338   8688686.5  4386.085502
1997  65.014676   9735063.5  4781.825478
2002  65.694923  10372918.5  5319.804524
2007  67.007423  10517531.0  6124.371109

# 데이터변환 : 데이터와 메서드를 일대일 대응시켜 계산
(데이터양은 변하지않는다.)

## 표준점수 : 데이터의 평균과 표준편차의 차이 

In [60]:
#표준점수 계산하는 함수 .......데이터의 평균과 표준편차의 차이....집계함수가 아니므로 건수변화 없음 
def my_zscore(x):
    return (x - x.mean()) / x.std()

In [62]:
df[df.year==1952]["lifeExp"]

0       28.801
12      55.230
24      43.077
36      30.015
48      62.485
         ...  
1644    40.412
1656    43.160
1668    32.548
1680    42.038
1692    48.451
Name: lifeExp, Length: 142, dtype: float64

In [19]:
#년도별 lifeExp열의 표준점수 계산 : 변환함수 transform메서드 이용  
transform_z = df.groupby('year').lifeExp.transform(my_zscore)
transform_z.head(5)

0   -1.656854
1   -1.731249
2   -1.786543
3   -1.848157
4   -1.894173
Name: lifeExp, dtype: float64

In [20]:
print(df.shape)

(1704, 6)


In [21]:
#데이터의 행의개수가 줄어들지 않는다...데이ㅣ터와 메서드를 1대1 대응시켜 계산하므로 
print(transform_z.shape)

(1704,)


## 누락값을 평균값으로 처리하기

In [22]:
#permutation (순열) ............. random한 정수 중복없이 갯수만큼 
#파라메터가 int이면 np.arange(x)
#파라메터가 배열이면 shuffle
np.random.permutation(10)    

array([9, 4, 5, 1, 0, 7, 6, 2, 3, 8])

In [23]:
np.random.permutation([1,2,3,4,5,6,7,8,9,10])

array([ 1,  6,  5,  9,  2,  8,  3,  7, 10,  4])

In [24]:
np.random.randint(1,10,10)

array([1, 6, 5, 5, 9, 2, 2, 3, 2, 2])

In [25]:
np.random.permutation([1,2,3,4,5,6,7,8,9,10])

array([ 1,  2, 10,  4,  7,  8,  6,  3,  9,  5])

In [26]:
import seaborn as sns 
import numpy as np

np.random.seed(42)
tips_10 = sns.load_dataset('tips').sample(10)
tips_10

total_bill   tip     sex smoker   day    time  size
24        19.82  3.18    Male     No   Sat  Dinner     2
6          8.77  2.00    Male     No   Sun  Dinner     2
153       24.55  2.00    Male     No   Sun  Dinner     4
211       25.89  5.16    Male    Yes   Sat  Dinner     4
198       13.00  2.00  Female    Yes  Thur   Lunch     2
176       17.89  2.00    Male    Yes   Sun  Dinner     2
192       28.44  2.56    Male    Yes  Thur   Lunch     2
124       12.48  2.52  Female     No  Thur   Lunch     2
9         14.78  3.23    Male     No   Sun  Dinner     2
101       15.38  3.00  Female    Yes   Fri  Dinner     2

In [27]:
aa = np.random.permutation(tips_10.index)
aa

array([176, 211, 198, 153, 101,   6, 192, 124,  24,   9], dtype=int64)

In [28]:
#10개의 sample데이터중에서 임의의 4개건의  total_bill열값을 NaN(누락값)으로 바꾼다. 
tips_10.loc[aa[:4], 'total_bill'] = np.NaN
print(tips_10)

     total_bill   tip     sex smoker   day    time  size
24        19.82  3.18    Male     No   Sat  Dinner     2
6          8.77  2.00    Male     No   Sun  Dinner     2
153         NaN  2.00    Male     No   Sun  Dinner     4
211         NaN  5.16    Male    Yes   Sat  Dinner     4
198         NaN  2.00  Female    Yes  Thur   Lunch     2
176         NaN  2.00    Male    Yes   Sun  Dinner     2
192       28.44  2.56    Male    Yes  Thur   Lunch     2
124       12.48  2.52  Female     No  Thur   Lunch     2
9         14.78  3.23    Male     No   Sun  Dinner     2
101       15.38  3.00  Female    Yes   Fri  Dinner     2


In [29]:
#누락값을 단순히 total_bill열의 평균값으로 채우면 안된다. 
#tips_10 데이타는 여성보다 남성의 데이터가 더 많음을 볼 수 있다 
#여성과 남성의 데이터를 구분하여 total_bill열의 평균값을 채우지않으면 여성의 데이터는 남성의 데이터에
#   영향을 받아 값이 훼손될 수 있다. 

#성별로 그룹을 하니 total_bill의 건수가 Male 3건, Female 1건이 누락되었음을 볼 수 있다 
count_sex = tips_10.groupby('sex').count() 
print(count_sex)

        total_bill  tip  smoker  day  time  size
sex                                             
Male             4    7       7    7     7     7
Female           2    3       3    3     3     3


In [30]:
#성별에 따른 평균값 
tips_10.groupby('sex').total_bill.mean()

sex
Male      17.9525
Female    13.9300
Name: total_bill, dtype: float64

In [31]:
#성별을 구분하여 total_bill열의 데이터를 받아 평균값을 구하고 null인 경우 이 평균을 return하는 함수이다. 
def fill_na_mean(x):
    avg = x.mean() 
    return x.fillna(avg)

In [32]:
#성별을 구분한 total_bill열의 데이터를 함수에 전달하여 평균값을 구한다음 평균이 null인경우 이를 return하여 
#tips_10 에 열을 추가한다. 
total_bill_group_mean = tips_10.groupby('sex').total_bill.transform(fill_na_mean)
tips_10['fill_total_bill'] = total_bill_group_mean
print(tips_10)

     total_bill   tip     sex smoker   day    time  size  fill_total_bill
24        19.82  3.18    Male     No   Sat  Dinner     2          19.8200
6          8.77  2.00    Male     No   Sun  Dinner     2           8.7700
153         NaN  2.00    Male     No   Sun  Dinner     4          17.9525
211         NaN  5.16    Male    Yes   Sat  Dinner     4          17.9525
198         NaN  2.00  Female    Yes  Thur   Lunch     2          13.9300
176         NaN  2.00    Male    Yes   Sun  Dinner     2          17.9525
192       28.44  2.56    Male    Yes  Thur   Lunch     2          28.4400
124       12.48  2.52  Female     No  Thur   Lunch     2          12.4800
9         14.78  3.23    Male     No   Sun  Dinner     2          14.7800
101       15.38  3.00  Female    Yes   Fri  Dinner     2          15.3800


## 데이터 필터링 사용하기 ─ filter 메서드

In [33]:
#tip 데이터를 불러와 데이터 크기 확인 
tips = sns.load_dataset('tips')
print(tips.shape)

(244, 7)


In [34]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [63]:
#size열의 데이터수
print(tips['size'].value_counts())

2    156
3     38
4     37
5      5
6      4
1      4
Name: size, dtype: int64


In [65]:
tips.sex.value_counts()

Male      157
Female     87
Name: sex, dtype: int64

In [67]:
tips.smoker.value_counts()

No     151
Yes     93
Name: smoker, dtype: int64

In [68]:
tips.day.value_counts()
tips.time.value_counts()

Dinner    176
Lunch      68
Name: time, dtype: int64

In [36]:
np.count_nonzero([0,1,1,1])

3

In [37]:
#size별 count의 합계
tips.groupby('size').agg([np.count_nonzero])

total_bill           tip           sex        smoker           day  \
     count_nonzero count_nonzero count_nonzero count_nonzero count_nonzero   
size                                                                         
1              4.0           4.0             4             4             4   
2            156.0         156.0           156           156           156   
3             38.0          38.0            38            38            38   
4             37.0          37.0            37            37            37   
5              5.0           5.0             5             5             5   
6              4.0           4.0             4             4             4   

              time  
     count_nonzero  
size                
1                4  
2              156  
3               38  
4               37  
5                5  
6                4

In [38]:
tips[tips["size"]==2].count()

total_bill    156
tip           156
sex           156
smoker        156
day           156
time          156
size          156
dtype: int64

In [39]:
#size별 ... 30번 이상의 주문이 있는 테이블만 추려서 데이터를 분석하려면?
tips_filtered = tips.groupby('size').filter(lambda x: x['size'].count() >= 30)

In [40]:
print(tips_filtered.shape)

(231, 7)


In [41]:
print(tips_filtered['size'].value_counts())

2    156
3     38
4     37
Name: size, dtype: int64


In [42]:
tips_filtered.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

## 그룹 오브젝트 저장하여 살펴보기

In [43]:
#임의의 데이터 10개 추출....항상 같은 데이터를 추출하려면 random_state값을 설정한다. 
tips_10 = sns.load_dataset('tips').sample(10, random_state=42) 
print(tips_10)

     total_bill   tip     sex smoker   day    time  size
24        19.82  3.18    Male     No   Sat  Dinner     2
6          8.77  2.00    Male     No   Sun  Dinner     2
153       24.55  2.00    Male     No   Sun  Dinner     4
211       25.89  5.16    Male    Yes   Sat  Dinner     4
198       13.00  2.00  Female    Yes  Thur   Lunch     2
176       17.89  2.00    Male    Yes   Sun  Dinner     2
192       28.44  2.56    Male    Yes  Thur   Lunch     2
124       12.48  2.52  Female     No  Thur   Lunch     2
9         14.78  3.23    Male     No   Sun  Dinner     2
101       15.38  3.00  Female    Yes   Fri  Dinner     2


In [44]:
#자료형이 그룹오브젝트이다. 
grouped = tips_10.groupby('sex')
print(grouped)

In [45]:
#그룹오브젝트에 포함된 그룹보기 (그룹별 인덱스를 볼 수 있다. )
print(grouped.groups)
grouped.sum()

{'Male': Int64Index([24, 6, 153, 211, 176, 192, 9], dtype='int64'), 'Female': Int64Index([198, 124, 101], dtype='int64')}


total_bill    tip  size
sex                            
Male        140.14  20.13    18
Female       40.86   7.52     6

In [46]:
tips.loc[198]+tips.loc[124]+tips.loc[101]

total_bill                 40.86
tip                         7.52
sex           FemaleFemaleFemale
smoker                  YesNoYes
day                  ThurThurFri
time            LunchLunchDinner
size                           6
dtype: object

## 그룹 오브젝트의 평균 구하기

In [47]:
avgs = grouped.mean() 
print(avgs)

        total_bill       tip      size
sex                                   
Male         20.02  2.875714  2.571429
Female       13.62  2.506667  2.000000


In [48]:
print(tips_10.columns)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')


## 그룹 오브젝트에서 데이터 추출하고 반복하기

In [49]:
# 그룹 오브젝트 활용 참고
# https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.groupby.html

In [50]:
female = grouped.get_group('Female') 
print(female)

     total_bill   tip smoker   day    time  size
198       13.00  2.00    Yes  Thur   Lunch     2
124       12.48  2.52     No  Thur   Lunch     2
101       15.38  3.00    Yes   Fri  Dinner     2


In [51]:
for sex_group in grouped:
    print(sex_group)

('Male',      total_bill   tip   sex smoker   day    time  size
24        19.82  3.18  Male     No   Sat  Dinner     2
6          8.77  2.00  Male     No   Sun  Dinner     2
153       24.55  2.00  Male     No   Sun  Dinner     4
211       25.89  5.16  Male    Yes   Sat  Dinner     4
176       17.89  2.00  Male    Yes   Sun  Dinner     2
192       28.44  2.56  Male    Yes  Thur   Lunch     2
9         14.78  3.23  Male     No   Sun  Dinner     2)
('Female',      total_bill   tip     sex smoker   day    time  size
198       13.00  2.00  Female    Yes  Thur   Lunch     2
124       12.48  2.52  Female     No  Thur   Lunch     2
101       15.38  3.00  Female    Yes   Fri  Dinner     2)


In [52]:
#데이터타입과 길이
for sex_group in grouped:
    print("성별:" , sex_group[0])
    print("값:", type(sex_group[1]) ,sex_group[1])
    print("---------------------------------------------------------------")
     
    

성별: Male
값: <class 'pandas.core.frame.DataFrame'>      total_bill   tip   sex smoker   day    time  size
24        19.82  3.18  Male     No   Sat  Dinner     2
6          8.77  2.00  Male     No   Sun  Dinner     2
153       24.55  2.00  Male     No   Sun  Dinner     4
211       25.89  5.16  Male    Yes   Sat  Dinner     4
176       17.89  2.00  Male    Yes   Sun  Dinner     2
192       28.44  2.56  Male    Yes  Thur   Lunch     2
9         14.78  3.23  Male     No   Sun  Dinner     2
---------------------------------------------------------------
성별: Female
값: <class 'pandas.core.frame.DataFrame'>      total_bill   tip     sex smoker   day    time  size
198       13.00  2.00  Female    Yes  Thur   Lunch     2
124       12.48  2.52  Female     No  Thur   Lunch     2
101       15.38  3.00  Female    Yes   Fri  Dinner     2
---------------------------------------------------------------


## 그룹 오브젝트 계산하고 살펴보기

In [53]:
bill_sex_time = tips_10.groupby(['sex', 'time'])
group_avg = bill_sex_time.mean() 

print(group_avg)

               total_bill       tip      size
sex    time                                  
Male   Lunch    28.440000  2.560000  2.000000
       Dinner   18.616667  2.928333  2.666667
Female Lunch    12.740000  2.260000  2.000000
       Dinner   15.380000  3.000000  2.000000


In [54]:
print(type(group_avg))

<class 'pandas.core.frame.DataFrame'>


In [55]:
print(group_avg.columns)

Index(['total_bill', 'tip', 'size'], dtype='object')


In [56]:
print(group_avg.index)

MultiIndex([(  'Male',  'Lunch'),
            (  'Male', 'Dinner'),
            ('Female',  'Lunch'),
            ('Female', 'Dinner')],
           names=['sex', 'time'])


In [57]:
group_method = tips_10.groupby(['sex', 'time']).mean().reset_index()  
print(group_method)

      sex    time  total_bill       tip      size
0    Male   Lunch   28.440000  2.560000  2.000000
1    Male  Dinner   18.616667  2.928333  2.666667
2  Female   Lunch   12.740000  2.260000  2.000000
3  Female  Dinner   15.380000  3.000000  2.000000


In [58]:
group_param = tips_10.groupby(['sex', 'time'], as_index=False).mean( )  
#위와 같은결과 
print(group_param)

      sex    time  total_bill       tip      size
0    Male   Lunch   28.440000  2.560000  2.000000
1    Male  Dinner   18.616667  2.928333  2.666667
2  Female   Lunch   12.740000  2.260000  2.000000
3  Female  Dinner   15.380000  3.000000  2.000000
