In [37]:
import numpy as np

In [39]:
#list : 여러타입 가능 
alist = ["1",2,3,4,5]
#array:하나의 타입만 가능(자동형변환), 속도빠르다. 
nparr = np.array(["1",2,3,4,5])
print(alist)
print(nparr)

['1', 2, 3, 4, 5]
['1' '2' '3' '4' '5']


In [45]:
#list : 여러타입 가능 , 벡터연산불가능 
alist = [1,2,3,4,5]
#array:하나의 타입만 가능(자동형변환), 속도빠르다.
#    벡터연산가능 
nparr = np.array([1,2,3,4,5])
print(alist)
print(alist*3) #반복
print(nparr+10) #벡터연산가능
print(nparr*3) #벡터연산가능

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[11 12 13 14 15]
[ 3  6  9 12 15]


In [46]:
#numpy array

arr1 = np.array([10,20,30,40,50])
arr2 = np.array([[10,20,30,40,50],[1,2,3,4,5]])
arr3 = np.array([[[1,2],[3,4],[5,6]],
                 [[7,8],[9,10],[11,12]]
                ])

In [50]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)


(5,)
(2, 5)
(2, 3, 2)
1
2
3


In [52]:
for i in arr1:
    print(i, end="**")

10**20**30**40**50**

In [55]:
for i in arr2:
    print(i )
    for j in i:
        print(j)
    

[10 20 30 40 50]
10
20
30
40
50
[1 2 3 4 5]
1
2
3
4
5


In [57]:
for i in arr3:
    print(i )
    print("--------------")
    

[[1 2]
 [3 4]
 [5 6]]
--------------
[[ 7  8]
 [ 9 10]
 [11 12]]
--------------


In [58]:
arr3[1][2][1]

12

In [62]:
type(arr1), arr1.dtype, type(arr3[1][2][1])

(numpy.ndarray, dtype('int32'), numpy.int32)

In [70]:
arr1 = np.array([1,2,3,4,5], dtype="int64")
arr1 = np.array([1,2,3,4,5], dtype="float")
arr1 = np.array([1000,2,3,4,5], dtype="str")
arr1 = arr1.astype(np.int32)
print(arr1)
arr1.dtype    #U1 : unicode 

[1000    2    3    4    5]


dtype('int32')

In [73]:
arr3.shape

(2, 3, 2)

In [77]:
#np.array([])

np.zeros(5)  #dtype=>float
np.zeros(5, dtype="int32")#-2147483648~2147483647
arr1 = np.zeros(5, dtype="U4")
arr1[0] = '파이썬프로그램'
arr1

array(['파이썬프', '', '', '', ''], dtype='<U4')

In [84]:
arr2 = np.ones((2,3), dtype=np.float64)
arr2[1][2] = 99.999
arr2

array([[ 1.   ,  1.   ,  1.   ],
       [ 1.   ,  1.   , 99.999]])

In [91]:
arr3 = np.empty((2,2,3), dtype=np.float64)
arr3

array([[[1.02475813e-311, 2.47032823e-322, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 1.61590357e+184]],

       [[6.51054141e-091, 1.24555556e-047, 5.50791210e+169],
        [2.33655640e-052, 3.99910963e+252, 1.46030983e-319]]])

In [92]:
arr= np.full((2,3), fill_value=100 )
arr

array([[100, 100, 100],
       [100, 100, 100]])

In [95]:
np.arange(10)
np.arange(1,10,2)
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [98]:
np.linspace(1,10,10)#시작, 끝, 갯수 
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [106]:
arr1 = np.array([1,2,3,4,5])
arr1.shape = 1,5  #차원이 바뀜 (2차원)
arr1.shape = 5,1  #차원이 바뀜 (2차원)
arr1.shape = 5,  #1차원
arr1

array([1, 2, 3, 4, 5])

In [120]:
arr3 = np.ones((2,3,4), dtype="int32")
arr3[0][0][1] = 99

arr3.ndim
arr3.size
arr3.shape
arr3.shape[0]
arr3.shape[1]
arr3.shape[2]

4

In [135]:
#1차원
A = np.arange(16) #0<=  <16
print(A.ndim, "차원")
print(A.shape, "shape")
print(A)
print(A.base)
print("-----------------------------------------")
B = A.reshape(4,4) #A,B :메모리공간을 공유 
print(B.ndim, "차원")
print(B.shape, "shape")
print(B)
print(B.base)
print("-----------------------------------------")
A[0] = 99
B[3][3] = 88
print(A)
print(B)
print("-----------------------------------------")
C = A.reshape(2,8).copy() #메모리공간 별도로 생성 
C[0] = -1  #행만사용하면 모든열을 의미 
print(C)
print(A) #영향없다. 

1 차원
(16,) shape
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
None
-----------------------------------------
2 차원
(4, 4) shape
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
-----------------------------------------
[99  1  2  3  4  5  6  7  8  9 10 11 12 13 14 88]
[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 88]]
-----------------------------------------
[[-1 -1 -1 -1 -1 -1 -1 -1]
 [ 8  9 10 11 12 13 14 88]]
[99  1  2  3  4  5  6  7  8  9 10 11 12 13 14 88]


In [142]:
A = np.arange(12)
B = A.reshape(2,2,-1)
C = B.ravel()  #1차원으로 만든다. 
C

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [143]:
A = np.arange(12)
A.resize(3,4)  #배열자체를 바꾸기 

A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [150]:
A = np.array([[1,2],[3,4]])
B = np.array([[99,88],[77,66]])

C= np.vstack((A,B))
D = np.hstack((A,B))
A[0] = -1
print(A)
print(C)
print(D)

[[-1 -1]
 [ 3  4]]
[[ 1  2]
 [ 3  4]
 [99 88]
 [77 66]]
[[ 1  2 99 88]
 [ 3  4 77 66]]


In [159]:
A = np.zeros((3,3))
B = np.ones((3,2))
C = np.hstack((A,B))
D = np.arange(10,160,10).reshape(3,-1)
E = np.vstack((C,D))
np.vstack((E,E))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [166]:
A = np.arange(10,60,10)
for i, su in enumerate(A):
    print(i, "번째 -->", su)

0 번째 --> 10
1 번째 --> 20
2 번째 --> 30
3 번째 --> 40
4 번째 --> 50


In [170]:
list(enumerate(A))

[(0, 10), (1, 20), (2, 30), (3, 40), (4, 50)]

In [168]:
list(zip(range(5), A))

[(0, 10), (1, 20), (2, 30), (3, 40), (4, 50)]

In [171]:
for i, su in zip(range(5), A):
    print(i, "번째 -->", su)

0 번째 --> 10
1 번째 --> 20
2 번째 --> 30
3 번째 --> 40
4 번째 --> 50


In [183]:
#열거형:enumerate
list(enumerate(A))

#zip(A,B) A집단과 B집단을 결합
list(zip(range(4), [5,6,7,8]))

[(0, 5), (1, 6), (2, 7), (3, 8)]

In [188]:
A = np.array([10,20,30,40,50,60]).reshape(2,-1)
B = np.array([1,2,3])
A+B

array([[11, 22, 33],
       [41, 52, 63]])

In [191]:
#브로드캐스팅: shape에 마지막이 같아야 가능 
A = np.array([10,20,30,40,50,60,70,80]).reshape(4,-1)#4,2
B = np.array([1,2])#
A+B

array([[11, 22],
       [31, 42],
       [51, 62],
       [71, 82]])

In [195]:
A = np.array([1,2,3,4])
B = np.array([1,20,3,4])

#A == B  #각각이 return 
np.all(A == B) #하나의 결과가 return 

False

In [198]:
np.where(A%2==0)# 위치return : (array([1, 3], dtype=int64),)

np.where(A%2==0, "짝수", "홀수")

array(['홀수', '짝수', '홀수', '짝수'], dtype='<U2')

In [200]:
np.add.reduce(A)

10

In [203]:
A

array([1, 2, 3, 4])

In [202]:
np.add.accumulate(A)

array([ 1,  3,  6, 10], dtype=int32)

In [224]:
np.random.choice(5,3)  #무작위수 0~5, 3개 선택
np.random.choice(6,10)  

array([5, 4, 1, 3, 5, 2, 5, 5, 1, 4])

In [262]:
A = np.array([10,20,30,40,50])
np.random.choice(A,4, replace=False) #비복원  


array([40, 10, 20, 30])

In [269]:
arr = np.array([ [4,  3,  5,  7],
                 [1, 12, 11,  9],
                 [2, 15,  1, 14]])
#전체합계
np.sum(arr)
# 행방향 합계
np.sum(arr, axis=0)
# 열방향 합계
np.sum(arr, axis=1)
# 행기준 정렬
np.sort(arr, axis=0)
# 열기준 정렬
np.sort(arr, axis=1)
# 정렬없이 순서얻기 

np.argsort(arr)


array([[1, 0, 2, 3],
       [0, 3, 2, 1],
       [2, 0, 3, 1]], dtype=int64)

In [270]:
arr

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

# pandas 

In [272]:
import pandas as pd

In [280]:
#data불러오기 : csv는 ","로 분리 , ./는 생략가능 
df = pd.read_csv("./data2/gapminder.tsv", sep="\t")
type(df)
df.head(2)
df.tail(2)
df.info()
#object type : string 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   country    1704 non-null   object 
 1   continent  1704 non-null   object 
 2   year       1704 non-null   int64  
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64  
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB


In [284]:
#1차원...series, 2차원 배열 ....dataframe 

s = pd.Series([10,20,30])
s.dtype, type(s)

(dtype('int64'), pandas.core.series.Series)

In [286]:
df = pd.DataFrame([["김",100],["박",200]],
                 columns=["이름","점수"]
                 )
df

이름   점수
0  김  100
1  박  200

In [288]:
#loc : 이름으로 접근 
#iloc : 순서로 접근 
df.loc[0, "점수"]
df.iloc[0, 1]

100

In [290]:
df.shape

(2, 2)

In [295]:
df.columns

Index(['이름', '점수'], dtype='object')

In [297]:
df_gap = pd.read_csv("./data2/gapminder.tsv", sep="\t")
df_gap.shape
df_gap.shape[0]
df_gap.shape[1]
df_gap.columns
df_gap.dtypes

country       object
continent     object
year           int64
lifeExp      float64
pop            int64
gdpPercap    float64
dtype: object

In [300]:
df_gap.head(n=3)

country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710

In [302]:
df_gap.iloc[1, 5]
df_gap.loc[1, "gdpPercap"]

820.8530296

In [307]:
df_gap.iloc[1, [0,2,4]]
type(df_gap.loc[1, ["country","year","pop"]])

df_gap.loc[[1,10,20], ["country","year","pop"]]
df_gap.loc[[1,10,20]]

country continent  year  lifeExp       pop    gdpPercap
1   Afghanistan      Asia  1957   30.332   9240934   820.853030
10  Afghanistan      Asia  2002   42.129  25268405   726.734055
20      Albania    Europe  1992   71.581   3326498  2497.437901

In [308]:
df_gap.iloc[99]

country      Bangladesh
continent          Asia
year               1967
lifeExp          43.453
pop            62821884
gdpPercap       721.186
Name: 99, dtype: object

In [310]:
df_gap.tail(n=1)

country continent  year  lifeExp       pop   gdpPercap
1703  Zimbabwe    Africa  2007   43.487  12311143  469.709298

In [311]:
df_gap.iloc[-1]
df_gap.iloc[1703]

country      Zimbabwe
continent      Africa
year             2007
lifeExp        43.487
pop          12311143
gdpPercap     469.709
Name: 1703, dtype: object

In [313]:
#슬라이싱
df_gap.loc[1:3, ["year","pop"]]
df_gap.loc[:, ["year","pop"]]

year       pop
0     1952   8425333
1     1957   9240934
2     1962  10267083
3     1967  11537966
4     1972  13079460
...    ...       ...
1699  1987   9216418
1700  1992  10704340
1701  1997  11404948
1702  2002  11926563
1703  2007  12311143

[1704 rows x 2 columns]

In [325]:
#df.이름== "김"
df[ df.점수==100 ]

이름   점수
0  김  100

In [331]:
#df_gap["year"]
#df_gap.year

df_gap[df_gap.year == 1957]["lifeExp"].mean()

51.50740112676054

In [334]:
#년도별 평균수명......?
df_gap.groupby("year")["lifeExp"].mean()

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [345]:
#대륙별 평균수명?
#df_gap.groupby(["continent","year"])[["lifeExp","pop"]].mean()

In [341]:
df_gap[df_gap.continent == "Africa"][["lifeExp","pop"]].mean()

lifeExp    4.886533e+01
pop        9.916003e+06
dtype: float64

In [350]:
country = 
   df_gap[df_gap.continent == "Africa"]["country"].unique()
len(country)


52

In [355]:
len(df_gap[df_gap.continent=='Asia']["country"].unique())

33

In [356]:
#그룹화한 갯수 세기 
df_gap[df_gap.continent=='Asia']["country"].nunique()

33

In [366]:
#칼럼추출 
df_gap["country"]
df_gap.loc[:, "country"]
df_gap.iloc[:, 0]
df_gap[["country","continent"]]

#row추출 
#df_gap[[True,False]]

#대륙이 아시아인 country
#df_gap[df_gap.continent == "Asia"]["country"]

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...     
1675    Yemen, Rep.
1676    Yemen, Rep.
1677    Yemen, Rep.
1678    Yemen, Rep.
1679    Yemen, Rep.
Name: country, Length: 396, dtype: object

In [368]:
pd.DataFrame([["A",100],["B",200]], columns=["이름","점수"])

이름   점수
0  A  100
1  B  200

In [383]:
#dictionary이용 .........인덱스를 설정하지 않으면 자동으로 index는 0,1,2와 같은 이름으로 부여된다.
scientists = pd.DataFrame({
    'Name': ['로절린드 프랭클린', '윌리엄 고셋'],
    'Occupation': ['생물학자', '통계학자'],
    'Born': ['1920-07-25', '1876-06-13'],
    'Died': ['1958-04-16', '1937-10-16'],
    'Age': [37, 61]})
scientists

Name Occupation        Born        Died  Age
0  로절린드 프랭클린       생물학자  1920-07-25  1958-04-16   37
1     윌리엄 고셋       통계학자  1876-06-13  1937-10-16   61

In [379]:
#칼럼접근 
scientists["Name"]
scientists[["Name","Occupation"]]

#행접근
scientists.loc[:, :]
scientists.loc[0, "Name"]
scientists.loc[0, ["Name","Occupation"]]
scientists.iloc[0, 0]
scientists.iloc[0, [0,1]]
scientists.iloc[[0,1], [0,1]]

Name Occupation
0  로절린드 프랭클린       생물학자
1     윌리엄 고셋       통계학자

In [380]:
scientists.index

RangeIndex(start=0, stop=2, step=1)

In [381]:
scientists.values

array([['로절린드 프랭클린', '생물학자', '1920-07-25', '1958-04-16', 37],
       ['윌리엄 고셋', '통계학자', '1876-06-13', '1937-10-16', 61]], dtype=object)

In [390]:
alist = [['로절린드 프랭클린', '생물학자', '1920-07-25', '1958-04-16', 37],
       ['윌리엄 고셋', '통계학자', '1876-06-13', '1937-10-16', 61]]

df = pd.DataFrame(alist, 
        columns=["이름","직업","출생일","사망일","나이"])
df.columns

Index(['이름', '직업', '출생일', '사망일', '나이'], dtype='object')

In [397]:
df["나이"].sum()
df["나이"].mean()
df["나이"].max()
df["나이"].min()

37

In [451]:
df = pd.read_csv("data2/scientists.csv")
df["Age"].mean()

59.125

In [407]:
#평균나이 이상인 과학자를 출력
#df[[False,True,True,True,False,False,False,True]]
df[df.Age>=df["Age"].mean()][["Name","Age"]]

Name  Age
1        William Gosset   61
2  Florence Nightingale   90
3           Marie Curie   66
7          Johann Gauss   77

In [410]:
#벡터연산 가능 
df.Age + 10
df.Age * 10

0    370
1    610
2    900
3    660
4    560
5    450
6    410
7    770
Name: Age, dtype: int64

In [424]:
a = df.Age  #[]
b = df.Age+10 #[]
df2 = pd.DataFrame(
    {"원래나이":a,"더한나이":b,"곱한나이":df.Age*10})



In [426]:
a.sort_index(ascending=False)

7    77
6    41
5    45
4    56
3    66
2    90
1    61
0    37
Name: Age, dtype: int64

In [428]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Name        8 non-null      object
 1   Born        8 non-null      object
 2   Died        8 non-null      object
 3   Age         8 non-null      int64 
 4   Occupation  8 non-null      object
dtypes: int64(1), object(4)
memory usage: 448.0+ bytes


In [429]:
scientists.head(2)

Name Occupation        Born        Died  Age
0  로절린드 프랭클린       생물학자  1920-07-25  1958-04-16   37
1     윌리엄 고셋       통계학자  1876-06-13  1937-10-16   61

In [431]:
#scientists.Born - scientists.Died

In [437]:
#역슬러쉬(다음줄에 계속됨을 의미한다. )
pd.to_datetime('20200817', format='%Y%m%d') - \
pd.to_datetime('20100817', format='%Y%m%d')

Timedelta('3653 days 00:00:00')

In [452]:
scientists = pd.read_csv("data2/scientists.csv")

In [453]:
#칼럼추가 : scientists.BornDT, scientists["BornDT"]
scientists["BornDT"] = pd.to_datetime(scientists.Born,format="%Y-%m-%d")
scientists["DiedDT"] = pd.to_datetime(scientists.Died,format="%Y-%m-%d")

In [454]:
scientists["days"] = scientists["DiedDT"]-scientists["BornDT"]

In [455]:
scientists

Name        Born        Died  Age          Occupation  \
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist   
1        William Gosset  1876-06-13  1937-10-16   61        Statistician   
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse   
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist   
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist   
5             John Snow  1813-03-15  1858-06-16   45           Physician   
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist   
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician   

      BornDT     DiedDT       days  
0 1920-07-25 1958-04-16 13779 days  
1 1876-06-13 1937-10-16 22404 days  
2 1820-05-12 1910-08-13 32964 days  
3 1867-11-07 1934-07-04 24345 days  
4 1907-05-27 1964-04-14 20777 days  
5 1813-03-15 1858-06-16 16529 days  
6 1912-06-23 1954-06-07 15324 days  
7 1777-04-30 1855-02-23 28422 days

In [449]:
scientists.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype          
---  ------      --------------  -----          
 0   Name        2 non-null      object         
 1   Occupation  2 non-null      object         
 2   Born        2 non-null      object         
 3   Died        2 non-null      object         
 4   Age         2 non-null      int64          
 5   BornDT      2 non-null      datetime64[ns] 
 6   DiedDT      2 non-null      datetime64[ns] 
 7   days        2 non-null      timedelta64[ns]
dtypes: datetime64[ns](2), int64(1), object(4), timedelta64[ns](1)
memory usage: 256.0+ bytes


In [456]:
scientists.columns

Index(['Name', 'Born', 'Died', 'Age', 'Occupation', 'BornDT', 'DiedDT',
       'days'],
      dtype='object')

In [460]:
scientists.columns

Index(['Name', 'Born', 'Died', 'Age', 'Occupation', 'BornDT', 'DiedDT',
       'days'],
      dtype='object')

In [465]:
scientists.drop(["Age", 'Born', 'Died'], 
                axis=1,inplace=True)
#inplace=True  .....원본에 적용하겠다의 의미 
#axis=1 ....열방향의 의미. 열을 삭제시 반드시 쓴다. 

In [466]:
scientists

Name          Occupation     BornDT     DiedDT       days
0     Rosaline Franklin             Chemist 1920-07-25 1958-04-16 13779 days
1        William Gosset        Statistician 1876-06-13 1937-10-16 22404 days
2  Florence Nightingale               Nurse 1820-05-12 1910-08-13 32964 days
3           Marie Curie             Chemist 1867-11-07 1934-07-04 24345 days
4         Rachel Carson           Biologist 1907-05-27 1964-04-14 20777 days
5             John Snow           Physician 1813-03-15 1858-06-16 16529 days
6           Alan Turing  Computer Scientist 1912-06-23 1954-06-07 15324 days
7          Johann Gauss       Mathematician 1777-04-30 1855-02-23 28422 days

In [474]:
#파일로 저장 
#파이썬 타입을 그대로 저장 : pickle로 저장 : dump(), load()
#csv, excel로 저장 
scientists.to_csv("data2/scientists_backup.csv")
scientists.to_excel("data2/scientists_backup.xls", index=False)

In [475]:
pd.read_csv("data2/scientists.csv")
pd.read_csv("data2/scientists_backup.csv")
pd.read_excel("data2/scientists_backup.xls")

Name          Occupation     BornDT     DiedDT   days
0     Rosaline Franklin             Chemist 1920-07-25 1958-04-16  13779
1        William Gosset        Statistician 1876-06-13 1937-10-16  22404
2  Florence Nightingale               Nurse 1820-05-12 1910-08-13  32964
3           Marie Curie             Chemist 1867-11-07 1934-07-04  24345
4         Rachel Carson           Biologist 1907-05-27 1964-04-14  20777
5             John Snow           Physician 1813-03-15 1858-06-16  16529
6           Alan Turing  Computer Scientist 1912-06-23 1954-06-07  15324
7          Johann Gauss       Mathematician 1777-04-30 1855-02-23  28422

In [476]:
df1 = pd.read_csv("data2/concat_1.csv")
df2 = pd.read_csv("data2/concat_2.csv")
df3 = pd.read_csv("data2/concat_3.csv")

In [486]:
df_all = pd.concat([df1, df2, df3]) #first_name||last_name


In [489]:
df_all.loc[3, :]  #이름 ...index이름이 3이다. 
#df_all.iloc[3, :] #순서 ...3번째 row

A    B    C    D
3   a3   b3   c3   d3
3   a7   b7   c7   d7
3  a11  b11  c11  d11

In [495]:
df_all = pd.concat([df1, df2, df3])
df_all = df_all.reset_index(drop=True) #drop=True기존index제거 
df_all.loc[3]  #index이름으로 접근
df_all.iloc[3] #순서로 접근 

A    a3
B    b3
C    c3
D    d3
Name: 3, dtype: object

In [503]:
new_series = pd.Series(["n1","n2","n3","n4"])
new_df = pd.DataFrame([["n1","n2","n3","n4"]],
                     columns=["A","B","C","D"]
                     )
#pd.concat([df1, new_series])
df_all2 = pd.concat([df1, new_df])
df_all2 = df_all2.reset_index(drop=True)
df_all2["추가"] =  pd.Series([10,20,30,40,50])
df_all2

A   B   C   D  추가
0  a0  b0  c0  d0  10
1  a1  b1  c1  d1  20
2  a2  b2  c2  d2  30
3  a3  b3  c3  d3  40
4  n1  n2  n3  n4  50

In [517]:
df1 = pd.read_csv("data2/concat_1.csv")

In [513]:
new_row_df = pd.DataFrame([["n1","n2","n3","n4"]], 
                          columns=["A","B","C","D"])


In [518]:
df1 = df1.append(new_row_df, ignore_index=True)
df1 = pd.concat([df1,new_row_df,new_row_df ])
df1.reset_index(drop=True)

A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3
4  n1  n2  n3  n4
5  n1  n2  n3  n4
6  n1  n2  n3  n4

In [ ]:
new_row_df2 = pd.concat([df1, new_row_df, new_row_df]) 
mydict = {"A":"p1", "B" : "p2", "C":"p3", "D":"p4"}
new_row_df3 = new_row_df2.append(mydict, ignore_index=True)

new_row_df4 = pd.DataFrame([mydict])
new_row_df3 = new_row_df3.append(new_row_df4, 
                                 ignore_index=True )
##데이터 프레임들을 연결한 후 index를 0부터 다시 부여한다. ignore_index=True

new_row_df3

In [534]:
df1 = pd.read_csv("data2/concat_1.csv")
df2 = pd.read_csv("data2/concat_2.csv")
df3 = pd.read_csv("data2/concat_3.csv")


In [520]:
#ignore_index=True 자동으로 index다시 부여 
df_all = pd.concat([df1, df2, df3], ignore_index=True)
df_all

A    B    C    D
0    a0   b0   c0   d0
1    a1   b1   c1   d1
2    a2   b2   c2   d2
3    a3   b3   c3   d3
4    a4   b4   c4   d4
5    a5   b5   c5   d5
6    a6   b6   c6   d6
7    a7   b7   c7   d7
8    a8   b8   c8   d8
9    a9   b9   c9   d9
10  a10  b10  c10  d10
11  a11  b11  c11  d11

In [522]:
df_all2 = pd.concat([df1, df2, df3], axis=1)
df_all2["A"]

A   A    A
0  a0  a4   a8
1  a1  a5   a9
2  a2  a6  a10
3  a3  a7  a11

In [523]:
df_all2 = pd.concat([df1, df2, df3], axis=1, 
                    ignore_index=True)
df_all2

0   1   2   3   4   5   6   7    8    9   10   11
0  a0  b0  c0  d0  a4  b4  c4  d4   a8   b8   c8   d8
1  a1  b1  c1  d1  a5  b5  c5  d5   a9   b9   c9   d9
2  a2  b2  c2  d2  a6  b6  c6  d6  a10  b10  c10  d10
3  a3  b3  c3  d3  a7  b7  c7  d7  a11  b11  c11  d11

In [541]:
df1.columns = ['A', 'B', 'C', 'D'] 
df2.columns = ['E', 'F', 'G', 'H'] 
df3.columns = ['A', 'C', 'F', 'H']

df1.index = [0, 1, 2, 3] 
df2.index = [4, 5, 6, 7] 
df3.index = [0, 2, 5, 7]


In [540]:
pd.concat([df1, df3], join="inner", ignore_index=True)

A    C
0   a0   c0
1   a1   c1
2   a2   c2
3   a3   c3
4   a8   b8
5   a9   b9
6  a10  b10
7  a11  b11

In [542]:
pd.concat([df1, df2, df3] )

A    B    C    D    E    F    G    H
0   a0   b0   c0   d0  NaN  NaN  NaN  NaN
1   a1   b1   c1   d1  NaN  NaN  NaN  NaN
2   a2   b2   c2   d2  NaN  NaN  NaN  NaN
3   a3   b3   c3   d3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   a4   b4   c4   d4
5  NaN  NaN  NaN  NaN   a5   b5   c5   d5
6  NaN  NaN  NaN  NaN   a6   b6   c6   d6
7  NaN  NaN  NaN  NaN   a7   b7   c7   d7
0   a8  NaN   b8  NaN  NaN   c8  NaN   d8
2   a9  NaN   b9  NaN  NaN   c9  NaN   d9
5  a10  NaN  b10  NaN  NaN  c10  NaN  d10
7  a11  NaN  b11  NaN  NaN  c11  NaN  d11

In [544]:
#특정위치의 날씨 정보에 필요한 데이터 집합들 불러오기 
#관측한 사람의 이름
person = pd.read_csv('data2/survey_person.csv') 
#관측위치
site = pd.read_csv('data2/survey_site.csv') 
#관측날짜
survey = pd.read_csv('data2/survey_survey.csv') 
#날씨정보
visited = pd.read_csv('data2/survey_visited.csv')

In [575]:
A = survey.merge(person, left_on="person", right_on="ident")
B = survey.merge(visited, left_on="taken", right_on="ident")
C = site.merge(visited, left_on="name", right_on="site")
D = A.merge(B, left_on="taken", right_on="taken")
D.merge(C, left_on="site", right_on="site")

taken person_x quant_x  reading_x ident_x   personal   family person_y  \
0      619     dyer     rad       9.82    dyer    William     Dyer     dyer   
1      619     dyer     rad       9.82    dyer    William     Dyer     dyer   
2      619     dyer     rad       9.82    dyer    William     Dyer     dyer   
3      619     dyer     rad       9.82    dyer    William     Dyer     dyer   
4      619     dyer     rad       9.82    dyer    William     Dyer     dyer   
..     ...      ...     ...        ...     ...        ...      ...      ...   
179    837     lake     sal       0.21    lake   Anderson     Lake     lake   
180    837     lake     sal       0.21    lake   Anderson     Lake      roe   
181    837      roe     sal      22.50     roe  Valentina  Roerich     lake   
182    837      roe     sal      22.50     roe  Valentina  Roerich     lake   
183    837      roe     sal      22.50     roe  Valentina  Roerich      roe   

    quant_y  reading_y  ident_y   site     dated_x   name    lat    long  \
0       rad       9.82      619   DR-1  1927-02-08   DR-1 -49.85 -128.57   
1       rad       9.82      619   DR-1  1927-02-08   DR-1 -49.85 -128.57   
2       rad       9.82      619   DR-1  1927-02-08   DR-1 -49.85 -128.57   
3       sal       0.13      619   DR-1  1927-02-08   DR-1 -49.85 -128.57   
4       sal       0.13      619   DR-1  1927-02-08   DR-1 -49.85 -128.57   
..      ...        ...      ...    ...         ...    ...    ...     ...   
179     sal       0.21      837  MSK-4  1932-01-14  MSK-4 -48.87 -123.40   
180     sal      22.50      837  MSK-4  1932-01-14  MSK-4 -48.87 -123.40   
181     rad       1.46      837  MSK-4  1932-01-14  MSK-4 -48.87 -123.40   
182     sal       0.21      837  MSK-4  1932-01-14  MSK-4 -48.87 -123.40   
183     sal      22.50      837  MSK-4  1932-01-14  MSK-4 -48.87 -123.40   

     ident     dated_y  
0      619  1927-02-08  
1      622  1927-02-10  
2      844  1932-03-22  
3      619  1927-02-08  
4      622  1927-02-10  
..     ...         ...  
179    837  1932-01-14  
180    837  1932-01-14  
181    837  1932-01-14  
182    837  1932-01-14  
183    837  1932-01-14  

[184 rows x 18 columns]

In [577]:
from numpy import NaN, nan, NAN

In [584]:
scientists = pd.DataFrame({ 
    'Name': ['Rosaline Franklin', 'William Gosset'], 
    'Occupation': ['Chemist', 'Statistician'], 
    'Born': ['1920-07-25', '1876-06-13'], 
    'Died': ['1958-04-16', '1937-10-16'], 
    'missing': [NaN, nan]}) 

#잘못된 표현
scientists.loc[1, "missing"] == nan
scientists.loc[1, "missing"] == NAN
scientists.loc[1, "missing"] == NaN

#맞는 표현 
pd.isnull(scientists.loc[1, "missing"])


True

In [592]:
lif_exp = df_gap.groupby("year")["lifeExp"].mean()

lif_exp.loc[1952]
lif_exp.loc[2002]

lif_exp[(lif_exp.index>=2000 ) & (lif_exp.index<=2010)]

year
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [604]:
df_ebola = pd.read_csv("data2/country_timeseries.csv")
#df_ebola.info()

#결측을 제외한 갯수 
df_ebola.count()


df_ebola.count()
122-93
#결측의 건수 
df_ebola.shape[0] - df_ebola.count()

Date                     0
Day                      0
Cases_Guinea            29
Cases_Liberia           39
Cases_SierraLeone       35
Cases_Nigeria           84
Cases_Senegal           97
Cases_UnitedStates     104
Cases_Spain            106
Cases_Mali             110
Deaths_Guinea           30
Deaths_Liberia          41
Deaths_SierraLeone      35
Deaths_Nigeria          84
Deaths_Senegal         100
Deaths_UnitedStates    104
Deaths_Spain           106
Deaths_Mali            110
dtype: int64

In [ ]:
df = pd.DataFrame([[nan,1, 1, 0, 0, 0, NaN , NAN]])
print(df)
print("null이 아닌것의 개수 :", np.count_nonzero(df))
print("-------------------------------------------------")
print(df.isnull())
print(np.count_nonzero(df.isnull()), "개")  #0(False)이 아닌것의 개수 ....null인것의 갯수

In [609]:
df = pd.DataFrame([[nan,1, 1, 0, 0, 0, NaN , NAN]])
#결측의 개수 
np.count_nonzero(df.isnull())

3

In [612]:
#결측의 건수 
np.count_nonzero(df_ebola.Cases_Guinea.isnull())

29

In [613]:
#결측제외건수 
df_ebola.Cases_Guinea.count()

93